export const TAB_MENU_SELECTED = 'TAB_MENU_SELECTED';
export const TAB_HOME_SELECTED = 'TAB_HOME_SELECTED';
export const TAB_ABOUT_SELECTED = 'TAB_ABOUT_SELECTED';
export const TAB_CONTACT_SELECTED = 'TAB_CONTACT_SELECTED';
